<%
  require 'bcdatabase'
  bcdb = Bcdatabase.load
%>
<%= bcdb.development  :bcsec, :enotis %>
<%= bcdb.test         :bcsec, :enotis %>
<%= bcdb.staging      :bcsec, :enotis %>
<%= bcdb.production   :bcsec, :enotis %>