<%
  require 'bcdatabase'
  bcdb = Bcdatabase.load
%>
<%= bcdb.development  :bcsec, :enotis %>
<%= bcdb.test         :bcsec, :enotis %>
<%= bcdb.staging      :bcsec, :enotis %>
<%= bcdb.production   :bcsec, :enotis %>

# change the user/password values and add the following to
# /etc/nubic/db/bcsec.yml

# enotis:
#   ldap_server: "registry.northwestern.edu"
#   ldap_user: "ldap_username"
#   ldap_password: "secret"
