 <%
   require 'bcdatabase'
   bcdb = Bcdatabase.load
 %>

<%= bcdb.development :local_oracle, :enotis_dev %>
<%= bcdb.test :local_oracle, :enotis_test %>
<%= bcdb.cucumber :local_oracle, :enotis_cuke %>

<%= bcdb.staging :bcstage, :enotis %>

<%= bcdb.production :bcprod, :enotis %>

