<%
  require 'bcdatabase'
  bcdb = Bcdatabase.load
%>

<%= bcdb.development :local_postgresql, :enotis %>

<%= bcdb.test :local_postgresql, :enotis_test %>

<%= bcdb.cucumber :local_postgresql, :enotis_test %>

<%= bcdb.hudson :pdev, :enotis_hudson %>

<%= bcdb.staging :pstage, :enotis %>

<%= bcdb.production :pprod, :enotis %>

<%= bcdb.cc_pers_test :local_oracle, :cc_pers_test %> # necessary for database cleaner to work with cc_pers_test

<%= bcdb.cc_pers_hudson :bcdev, :cc_pers_hudson_enotis %>
