<%
  require 'bcdatabase'
  bcdb = Bcdatabase.load
%>
<%= bcdb.development  :eirb, :enotis_test %>
<%= bcdb.test         :eirb, :enotis_test %>
<%= bcdb.staging      :eirb, :enotis_test %>
<%= bcdb.production   :eirb, :enotis_test %>

# change the user/password values and add the following to
# /etc/nubic/db/eirb.yml

# default:
#   url: "http://riseirbsvr3.itcs.northwestern.edu/ClickXWebServices/DataManagement/SearchServices.asmx?WSDL"
#   username: "eirb_username"
#   password: "secret"
# 
# enotis_test:
#   storename: "eIRB-Test"
# 
