development:
  url: "http://riseirbsvr3.itcs.northwestern.edu/ClickXWebServices/DataManagement/SearchServices.asmx?WSDL"
  username: "blc615"
  password: "nuc#1blc"
  storename: "eIRB-Test"

test:
  url: "http://riseirbsvr3.itcs.northwestern.edu/ClickXWebServices/DataManagement/SearchServices.asmx?WSDL"
  username: "blc615"
  password: "nuc#1blc"
  storename: "eIRB-Test"

