development:
  host: localhost
  port: 6379

production:
  host: localhost
  port: 6379

staging:
  host: q.staging
  port: 6379

production:
  host: q.prod
  port: 6379

hudson:
  host: localhost
  port: 6379

test:
  host: localhost
  port: 6379
  db: 1
  
cucumber:
  host: localhost
  port: 6379
  db: 1