users:
  blc615:               # username
    password: secret          # password for :user auth (optional)
    portals:            # portal & group auth info (optional)
      - ENOTIS:             # A portal with simple groups
        - Admin
  brian:
    password: secret          # password for :user auth (optional)
    portals:            # portal & group auth info (optional)
      - ENOTIS:             # A portal with simple groups
        - User
  daw286:               # username
    password: secret          # password for :user auth (optional)
    portals:            # portal & group auth info (optional)
      - ENOTIS:             # A portal with simple groups
        - Admin
  david:
    password: secret          # password for :user auth (optional)
    portals:            # portal & group auth info (optional)
      - ENOTIS:             # A portal with simple groups
        - User
  lmw351:               # username
    password: secret       # password for :user auth (optional)
    portals:            # portal & group auth info (optional)
      - ENOTIS:             # A portal with simple groups
        - Admin
  laura:
    password: secret          # password for :user auth (optional)
    portals:            # portal & group auth info (optional)
      - ENOTIS:             # A portal with simple groups
        - User
  myo628:               # username
    password: secret           # password for :user auth (optional)
    portals:            # portal & group auth info (optional)
      - ENOTIS:             # A portal with simple groups
        - Admin
  yoon:
    password: secret          # password for :user auth (optional)
    portals:            # portal & group auth info (optional)
      - ENOTIS:             # A portal with simple groups
        - User
  wakibbe:               # username
    password: secret          # password for :user auth (optional)
    portals:            # portal & group auth info (optional)
      - ENOTIS:             # A portal with simple groups
        - Admin
  warren:
    password: secret          # password for :user auth (optional)
    portals:            # portal & group auth info (optional)
      - ENOTIS:             # A portal with simple groups
        - User
groups:                  # groups for hierarchical portals
  ENOTIS:                 # (these aren't real NOTIS groups)
    - Admin:
      - User
